name: Librespotify streamer for whole-home audio
description: Addon for streaming spotify to the whole home
version: 0.9.5
slug: spothome
startup: application
boot: auto
host_network: true
#host_dbus: true
ports:
  6000/tcp: 6000
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
